version: 2

models:
  - name: dim_products
    columns:
      - name: product_id
        data_tests: [unique, not_null]

  - name: dim_sellers
    columns:
      - name: seller_id
        data_tests: [unique, not_null]

  - name: dim_customers
    columns:
      - name: customer_unique_id
        data_tests: [unique, not_null]
      - name: lifetime_order_count
        data_tests:
          - not_null

  - name: fct_order_items
    columns:
      - name: order_id
        data_tests: [not_null]
      - name: product_id
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id
      - name: seller_id
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_sellers')
                field: seller_id

  - name: fct_payments
    columns:
      - name: order_id
        data_tests: [unique, not_null]

  - name: fct_reviews
    columns:
      - name: order_id
        data_tests: [unique, not_null]

  - name: fct_orders
    columns:
      - name: order_id
        data_tests: [unique, not_null]
      - name: customer_unique_id
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_unique_id
